sf_project/config/routes.rb
SfProject::Application.routes.draw do
  get "my_pages/home"

  get "my_pages/help"
 
  get "my_pages/test"

  get "pages/home"

  get "pages/help"

  resources :posts

  resources :users

  resources :project_assignements

  resources :projects

  resources :employees

end

sf_project/app/models/project_assignement.rb
class ProjectAssignement < ActiveRecord::Base
  attr_accessible :employee_id, :project_id
  belongs_to :project
  belongs_to :employee
end

sf_project/app/controllers/project_assignements_controller.rb
class ProjectAssignementsController < ApplicationController
  # GET /project_assignements
  # GET /project_assignements.json
  def index
    @project_assignements = ProjectAssignement.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @project_assignements }
    end
  end

  # GET /project_assignements/1
  # GET /project_assignements/1.json
  def show
    @project_assignement = ProjectAssignement.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project_assignement }
    end
  end

  # GET /project_assignements/new
  # GET /project_assignements/new.json
  def new
    @project_assignement = ProjectAssignement.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project_assignement }
    end
  end

  # GET /project_assignements/1/edit
  def edit
    @project_assignement = ProjectAssignement.find(params[:id])
  end

  # POST /project_assignements
  # POST /project_assignements.json
  def create
    @project_assignement = ProjectAssignement.new(params[:project_assignement])

    respond_to do |format|
      if @project_assignement.save
        format.html { redirect_to @project_assignement, notice: 'Project assignement was successfully created.' }
        format.json { render json: @project_assignement, status: :created, location: @project_assignement }
      else
        format.html { render action: "new" }
        format.json { render json: @project_assignement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /project_assignements/1
  # PUT /project_assignements/1.json
  def update
    @project_assignement = ProjectAssignement.find(params[:id])

    respond_to do |format|
      if @project_assignement.update_attributes(params[:project_assignement])
        format.html { redirect_to @project_assignement, notice: 'Project assignement was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project_assignement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /project_assignements/1
  # DELETE /project_assignements/1.json
  def destroy
    @project_assignement = ProjectAssignement.find(params[:id])
    @project_assignement.destroy

    respond_to do |format|
      format.html { redirect_to project_assignements_url }
      format.json { head :no_content }
    end
  end
end

sf_project/app/helpers/project_assignements_helper.rb
module ProjectAssignementsHelper
end

sf_project/app/views/project_assignements/_form.html.erb
<%= form_for(@project_assignement) do |f| %>
  <% if @project_assignement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project_assignement.errors.count, "error") %> prohibited this project_assignement from being saved:</h2>

      <ul>
      <% @project_assignement.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :employee_id %><br />
    <%= f.number_field :employee_id %>
  </div>
  <div class="field">
    <%= f.label :project_id %><br />
    <%= f.number_field :project_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

sf_project/app/views/project_assignements/edit.html.erb
<h1>Editing project_assignement</h1>

<%= render 'form' %>

<%= link_to 'Show', @project_assignement %> |
<%= link_to 'Back', project_assignements_path %>

sf_project/app/views/project_assignements/index.html.erb
<h1>Listing project_assignements</h1>

<table>
  <tr>
    <th>Employee</th>
    <th>Project</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @project_assignements.each do |project_assignement| %>
  <tr>
    <td><%= project_assignement.employee_id %></td>
    <td><%= project_assignement.project_id %></td>
    <td><%= link_to 'Show', project_assignement %></td>
    <td><%= link_to 'Edit', edit_project_assignement_path(project_assignement) %></td>
    <td><%= link_to 'Destroy', project_assignement, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Project assignement', new_project_assignement_path %>

sf_project/app/views/project_assignements/new.html.erb
<h1>New project_assignement</h1>

<%= render 'form' %>

<%= link_to 'Back', project_assignements_path %>

sf_project/app/views/project_assignements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Employee:</b>
  <%= @project_assignement.employee_id %>
</p>

<p>
  <b>Project:</b>
  <%= @project_assignement.project_id %>
</p>


<%= link_to 'Edit', edit_project_assignement_path(@project_assignement) %> |
<%= link_to 'Back', project_assignements_path %>